cmd/nebula/cmd_resolve.go
cmd/nebula/nebula.go
deploy/docker-compose.yml
pkg/config/config.go
pkg/db/client.go

I was working on a helm chart to deploy this. If you want to have a gander, that can be seen here https://github.com/filecoin-project/helm-charts/pull/121
Our postgres database is configured limit connections only from secure sslmodes, so I added another flag to parameterize it and changed the default.

postgres ssl

---

cmd/nebula/cmd_resolve.go

Change looks noisy because indentation has changed. Hide whitespace changes with https://github.com/dennis-tra/nebula/pull/31/files?w=1

Resolve each multiaddress in separate transaction, rollback txn on error

---

README.md
pkg/config/bootstrap.go
pkg/config/config.go
pkg/core/handler_crawl.go
pkg/core/queue.go

- This PR adds support for Celestia Mainnet, which was launched ~2w ago by adding the `CELESTIA` network key. A network crawl only takes a few seconds.
- This PR also updates the Arabica and Mocha network defaults (though I learned that this seems to be a moving target)
@wondertan do the following numbers make sense?
```
INFO[0024] Crawl summary:                               
INFO[0024]                                              
INFO[0024] Dial Error                                    count=13 value=connection_refused
INFO[0024] Dial Error                                    count=8 value=connection_reset_by_peer
INFO[0024] Dial Error                                    count=24 value=io_timeout
INFO[0024] Dial Error                                    count=11 value=no_public_ip …
```

Celestia Mainnet Support

---

discv5/crawler.go

Nebula used to store only the discv5 maddrs crafted from the ENR in the DB. It should store all reported multiaddresses (including quic).

fix: store reported discv5 listen maddrs in the DB

---

discv5/crawler.go

Until now, a visit has a crawl error as soon as 1 request fails. 
Change the behavior to log a crawl error only if all requests fail.
Note that from the code, as long as there is an error with a bucket, all the next buckets will NOT be queried. So the crawl considers that all requests have failed.

discv5: only store crawl error if no query succeeded

---

discv5/crawler.go
discv5/crawler_test.go

If all runs of the loop failed, then `ErrorBits` is a power of two minus one, and we should keep the `result.Error`. Otherwise, at least one iteration was successful, set `result.Error` to `nil`.

fix: crawl_error detection

---

discv5/crawler.go

Because we're storing the reported listen addrs from a certain peer: https://github.com/dennis-tra/nebula/pull/54
we don't track what exactly was written in the ENR. This PR adds three additional fields to the peer properties.

feat: store additional ENR fields

---

.github/workflows/goreleaser.yml

Coming from Issue #60 and from the previous fix attempt at #62 
It seems that the Ubuntu-Latest machine spawned to create the binaries is unable to find C dependencies to build the binaries. This PR aims to fix that.

Fix Gorelease at Github Actions 

---

.github/workflows/goreleaser.yml
.goreleaser.yaml

#63 fix the GCC missing dependencies to compile the binaries. However, it was missing the specific CC (C Compiler binaries for each of the OS and Arch we want to compile for)
This PR specifies those missing binaries.

Specify CCompiler binaries for each OS and Arch

---

.github/workflows/goreleaser.yml
.goreleaser.yaml

The compilation of Nebula requires some CGO dependencies, which heavily complicate the cross-compilation efforts. This PR aims to solve #60 using the Docker images provided by [goreleaser/goreleaser-cross](https://github.com/goreleaser/goreleaser-cross)
_NOTE: Super important to rely on the `ghcr.io/gorelease-cross` images, as there are some C libs missing at the DockerHub images._ :(
The compilation works fine locally (with the listed GOOS and GOARCH) when running:
```
docker run --rm \
-v ./:/workspace \
-w /workspace \
-v /var/run/docker.sock:/var/run/docker.sock \
ghcr.io/goreleaser/goreleaser-cross:v1.19.6 build --snapshot --clean --config .goreleaser.yaml
```
which reports:
```
• starting build...
• loading config file                              file=.goreleaser.yaml
• loading …
```

Add ghcr.io/gorelease-cross docker to cross-compile binaries

---

.github/workflows/goreleaser.yml

After successfully cross-compiling nebula for other GOOS and GOARCHs, only changing the missing `release` flag at the `goreleaser` GitHub actions is needed (side effect from the local testing)

Make release of resulting dist/binaries from github actions

---

db/client_db.go

As far as I understand, the db initialization happens at the start of the crawl.
When the db is initialized, this is where the [ensurePartitions](https://github.com/dennis-tra/nebula/blob/d88a08f2b6492d3acc42b79a1a72db1c752b9d65/db/client_db.go#L213) happens. However, for each start of the crawl, we do not have the current crawl ID until after the crawl actually starts, so the previous crawl ID is the max ID.

fix: crawlID should not be n-1 during ensurePartition

---

go.mod
go.sum

This PR upgrades the `github.com/volatiletech/strmangle` library from `v0.0.5` to `v0.0.6`.
When generating the models using `make models`, the model generated codes containing `strmangle.SetIntersect`, which isn't supported in `v0.0.5`.

Upgrade volatiletech/strmangle to v0.0.6

---

config/bootstrap.go
config/config.go
libp2p/driver_crawler.go

Since the Avail Goldberg testnet has been deprecated, the bootnodes listed in [`./config/bootstrap.go](https://github.com/dennis-tra/nebula/blob/13c06a3e65a72c7b86e6120aaa856d711bf56d8a/config/bootstrap.go#L232) are outdated.
This PR aims to remove the deprecated bootnodes in favour of the new ones for the Avail Turin testnet ones.
*Works fine locally:*
```
$ nebula --dry-run crawl --network AVAIL_TURIN --limit 100
INFO[0000] Starting Nebula crawler...                   
INFO[0000] Queried 0 bootstrap peers                     limit=10
2024/07/01 15:56:40 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.
INFO[0000] Handled worker result …
```

Update Avail bootnodes

---

config/bootstrap.go
config/config.go
libp2p/driver_crawler.go

last week, Avail launched their mainnet officially. In order to set up Nebula to run in that network as well, we need to add support for both: the `AVAIL_MAINNET_FN` and `AVAIL_MAINNET_LC` networks.

Add Avail Mainnet bootstrappers

---

discv5/crawler.go
discv5/driver_crawler.go

This PR adds the functionality to parse the QUIC ENR entry.
If Nebula was able to connect to an ethereum node it also stores the transport that's used

eth: parse quic ENR entry

---

cmd/nebula/cmd_crawl.go
core/core.go
core/core_test.go
core/engine.go
discv4/crawler.go
discv4/driver_crawler.go
discv5/driver_crawler.go
go.mod
go.sum
libp2p/driver_crawler.go

This PR introduces the concept of deduplication keys.
A deduplication key is a unique string used for deduplication of crawl tasks. For example, in discv4 and discv5 we might want to crawl the same peer (as identified by its public key) multiple times when we find new ENR's for it. If the deduplication key was just the public key, we would only crawl it only once. If we later find newer ENR's for the same peer with different network addresses, we would skip that peer. On the other hand, if the deduplication key was the entire ENR, we would crawl the same peer with different (potentially newer) connectivity information again.

Introduce deduplication key

---

db/errors.go
discv5/crawler.go
discv5/driver_crawler.go
libp2p/crawler.go
libp2p/crawler_p2p.go
libp2p/driver_crawler.go

Context
- https://discuss.libp2p.io/t/rust-go-interop-idle-connection-timeout-race-condition/2470/3
- https://github.com/libp2p/rust-libp2p/issues/4912

fix: don't wait for the identify exchange to complete before draining buckets

---

libp2p/rpc.go

* Context: https://github.com/libp2p/go-libp2p-kad-dht/issues/1015
* `go-msgio/protoio` is deprecated and should be replaced by `go-msgio/pbio`
@dennis-tra let me know if it fixes the panic

fix: replace deprecated protoio with pbio

---

db/pg.go

Fixed dataraces encountered when `--neighbors=true`.

Make neighbors routing tables access mutual exclusive

---

discv5/enr.go

We observed the following out of bounds exception:
```text
panic: runtime error: index out of range [7] with length 5 goroutine 14309 [running]:
encoding/binary.bigEndian.Uint64(...)
/usr/local/go/src/encoding/binary/binary.go:186
github.com/dennis-tra/nebula-crawler/discv5.(*ENREntryAttnets).DecodeRLP(0xc02749eee8, 0x1f2de20?)
/build/discv5/enr.go:143 +0x1a9
github.com/ethereum/go-ethereum/rlp.decodeDecoder(0xc00e0e1c70, {0x1fd6480?, 0xc02749eee8?, 0xc03af70990?})
/go/pkg/mod/github.com/probe-lab/go-ethereum@v0.0.0-20241105111838-95c73e73f0fd/rlp/decode.go:542 +0x96
github.com/ethereum/go-ethereum/rlp.(*Stream).Decode(0xc00e0e1c70, {0x1f2de20?, 0xc02749eee8?})
/go/pkg/mod/github.com/probe-lab/go-ethereum@v0.0.0-20241105111838-95c73e73f0fd/rlp/decode.go:950 +0x1f0 …
```

fix: attnets decoding out of bound exception
